package fr.lamacq.utils

import fr.lamacq.vo.XmlPdf

val XmlToPdfStructure: Array<XmlPdf> = arrayOf(
    XmlPdf("Exploitant",
        arrayOf(arrayOf("dossierConsultation", "listeDesOuvrages", "ouvrage", "contact", "societe"))),
    XmlPdf("Destinataire",
        arrayOf(
            arrayOf("dossierConsultation", "listeDesOuvrages", "ouvrage", "contact", "nom", "NomFamille"),
            arrayOf("dossierConsultation", "listeDesOuvrages", "ouvrage", "contact", "prenom", "Prenom"),
            arrayOf("dossierConsultation", "listeDesOuvrages", "ouvrage", "contact", "agence"))),
    XmlPdf("Complement_adresse",
        arrayOf(arrayOf("dossierConsultation", "listeDesOuvrages", "ouvrage", "contact", "complement"))),
    XmlPdf("No_voie",
        arrayOf(
            arrayOf("dossierConsultation", "listeDesOuvrages", "ouvrage", "contact", "numero"),
            arrayOf("dossierConsultation", "listeDesOuvrages", "ouvrage", "contact", "voie"))),
    XmlPdf("Lieudit_BP",
        arrayOf(arrayOf("dossierConsultation", "listeDesOuvrages", "ouvrage", "contact", "lieuDitBP"))),
    XmlPdf("CP",
        arrayOf(arrayOf("dossierConsultation", "listeDesOuvrages", "ouvrage", "contact", "codePostal"))),
    XmlPdf("Commune",
        arrayOf(arrayOf("dossierConsultation", "listeDesOuvrages", "ouvrage", "contact", "commune"))),
    XmlPdf("Pays",
        arrayOf(arrayOf("dossierConsultation", "listeDesOuvrages", "ouvrage", "contact", "codePays")))
)

val XmlToPdfDt: Array<XmlPdf> = arrayOf(
    XmlPdf("No_GU_DT",
        arrayOf(arrayOf("dossierConsultation", "DT", "noConsultationDuTeleserviceSeize"))),
    XmlPdf("No_affaire_responsable_projet",
        arrayOf(arrayOf("dossierConsultation", "DT", "noAffaireDuResponsableDuProjet"))),
    XmlPdf("Jour_DT",
        arrayOf(arrayOf("dossierConsultation", "DT", "dateDeLaDeclaration")),"DateDate"),
    XmlPdf("Mois_DT",
        arrayOf(arrayOf("dossierConsultation", "DT", "dateDeLaDeclaration")),"DateMonth"),
    XmlPdf("Annee_DT",
        arrayOf(arrayOf("dossierConsultation", "DT", "dateDeLaDeclaration")),"DateFullYear"),
    XmlPdf("ResponsableProjetCase",
        arrayOf(arrayOf("dossierConsultation", "DT", "typeEntite"))),
    XmlPdf("Declaration_conjointe",
        arrayOf(arrayOf("dossierConsultation", "DT", "declarationConjointeDTDICT"))),
    XmlPdf("Responsable_projet",
        arrayOf(arrayOf("dossierConsultation", "DT", "responsableDuProjet", "denomination"))),
    XmlPdf("Pays_DT",
        arrayOf(arrayOf("dossierConsultation", "DT", "responsableDuProjet", "pays"))),
    XmlPdf("Siret1_DT",
        arrayOf(arrayOf("dossierConsultation", "DT", "responsableDuProjet", "noSiret"))),
    XmlPdf("Siret2_DT",
        arrayOf(arrayOf("dossierConsultation", "DT", "responsableDuProjet", "noSiret"))),
    XmlPdf("Siret3_DT",
        arrayOf(arrayOf("dossierConsultation", "DT", "responsableDuProjet", "noSiret"))),
    XmlPdf("Siret4_DT",
        arrayOf(arrayOf("dossierConsultation", "DT", "responsableDuProjet", "noSiret"))),
    XmlPdf("Organisme_Service",
        arrayOf(arrayOf("dossierConsultation", "DT", "representantDuResponsableDeProjet", "denomination"))),
    XmlPdf("Complement_adresse_DT",
        arrayOf(arrayOf("dossierConsultation", "DT", "representantDuResponsableDeProjet", "complementService"))),
    XmlPdf("Numero_DT",
        arrayOf(arrayOf("dossierConsultation", "DT", "representantDuResponsableDeProjet", "numero"))),
    XmlPdf("Voie_DT",
        arrayOf(arrayOf("dossierConsultation", "DT", "representantDuResponsableDeProjet", "voie"))),
    XmlPdf("Lieudit_BP_DT",
        arrayOf(arrayOf("dossierConsultation", "DT", "representantDuResponsableDeProjet", "lieuDitBP"))),
    XmlPdf("CP_DT",
        arrayOf(arrayOf("dossierConsultation", "DT", "representantDuResponsableDeProjet", "codePostal"))),
    XmlPdf("Commune_DT",
        arrayOf(arrayOf("dossierConsultation", "DT", "representantDuResponsableDeProjet", "commune"))),
    XmlPdf("Personne_contacter_DT",
        arrayOf(arrayOf("dossierConsultation", "DT", "representantDuResponsableDeProjet", "personneAcontacter"))),
    XmlPdf("Telephone_DT",
        arrayOf(arrayOf("dossierConsultation", "DT", "representantDuResponsableDeProjet", "tel"))),
    XmlPdf("Fax_DT",
        arrayOf(arrayOf("dossierConsultation", "DT", "representantDuResponsableDeProjet", "fax"))),
    XmlPdf("Courriel_DT",
        arrayOf(arrayOf("dossierConsultation", "DT", "representantDuResponsableDeProjet", "courriel"))),
    XmlPdf("Adresse_DT",
        arrayOf(arrayOf("dossierConsultation", "DT", "emplacementDuProjet", "adresse"))),
    XmlPdf("CP_Travaux_DT",
        arrayOf(arrayOf("dossierConsultation", "DT", "emplacementDuProjet", "CP"))),
    XmlPdf("Commune_Travaux_DT",
        arrayOf(arrayOf("dossierConsultation", "DT", "emplacementDuProjet", "communePrincipale"))),
    XmlPdf("Nb_Communes_DT",
        arrayOf(arrayOf("dossierConsultation", "DT", "emplacementDuProjet", "nombreDeCommunes"))),
    XmlPdf("Souhait_recepisse_DTDICTconjoint",
        arrayOf(arrayOf("dossierConsultation", "DT", "souhaitsPourLeRecepisse", "souhaiteRecevoirLeRecepisse"))),
    XmlPdf("Mode_recepisse_DT",
        arrayOf(
            arrayOf("dossierConsultation", "DT", "souhaitsPourLeRecepisse", "modeReceptionElectronique"),
            arrayOf("dossierConsultation", "DT", "souhaitsPourLeRecepisse", "modeReceptionCourrier"),
            arrayOf("dossierConsultation", "DT", "souhaitsPourLeRecepisse", "modeReceptionFax")), "NodeName"), // ???
    XmlPdf("Plans_taille_DT",
        arrayOf(arrayOf("dossierConsultation", "DT", "souhaitsPourLeRecepisse", "modeReceptionElectronique", "tailleDesPlans"))),
    XmlPdf("PlanCouleur_DT",
        arrayOf(arrayOf("dossierConsultation", "DT", "souhaitsPourLeRecepisse", "modeReceptionElectronique", "couleurDesPlans"))),
    XmlPdf("PlansVectoriels_DT",
        arrayOf(arrayOf("dossierConsultation", "DT", "souhaitsPourLeRecepisse", "modeReceptionElectronique", "souhaitDePlansVectoriels"))),
    XmlPdf("Plans_Formats_DT",
        arrayOf(arrayOf("dossierConsultation", "DT", "souhaitsPourLeRecepisse", "modeReceptionElectronique", "formatDesPlansVectoriels"))),
    XmlPdf("Nature_Travaux1_DT",
        arrayOf(arrayOf("dossierConsultation", "DT", "projetEtSonCalendrier", "natureDesTravaux"))),
    XmlPdf("Nature_Travaux2_DT",
        arrayOf(arrayOf("dossierConsultation", "DT", "projetEtSonCalendrier", "natureDesTravaux"))),
    XmlPdf("Nature_Travaux3_DT",
        arrayOf(arrayOf("dossierConsultation", "DT", "projetEtSonCalendrier", "natureDesTravaux"))),
    XmlPdf("Nature_Travaux4_DT",
        arrayOf(arrayOf("dossierConsultation", "DT", "projetEtSonCalendrier", "natureDesTravaux"))),
    XmlPdf("Nature_Travaux5_DT",
        arrayOf(arrayOf("dossierConsultation", "DT", "projetEtSonCalendrier", "natureDesTravaux"))),
    XmlPdf("Projet_DT",
        arrayOf(arrayOf("dossierConsultation", "DT", "projetEtSonCalendrier", "decrivezLeProjet")),"MultiLine1"), //
    XmlPdf("Projet2_DT",
        arrayOf(arrayOf("dossierConsultation", "DT", "projetEtSonCalendrier", "decrivezLeProjet")),"MultiLine2"),
    XmlPdf("TST",
        arrayOf(arrayOf("dossierConsultation", "DT", "projetEtSonCalendrier", "emploiDeTechniquesSansTranchees"))),
    XmlPdf("Distance_m_DT",
        arrayOf(arrayOf("dossierConsultation", "DT", "projetEtSonCalendrier", "distanceMinimaleEntreLesTravauxEtLaLigneElectrique"))),
    XmlPdf("Distance_cm_DT",
        arrayOf(arrayOf("dossierConsultation", "DT", "projetEtSonCalendrier", "distanceMinimaleEntreLesTravauxEtLaLigneElectrique"))),
    XmlPdf("Prox_reseaux_elec_CaseDT",
        arrayOf(arrayOf("dossierConsultation", "DT", "projetEtSonCalendrier", "souhaitLesPlansDesReseauxElectriqueAeriens"))),
    XmlPdf("Jour_travaux_DT",
        arrayOf(arrayOf("dossierConsultation", "DT", "projetEtSonCalendrier", "datePrevuePourLeCommencementDesTravaux")),"DateDate"),
    XmlPdf("Mois_travaux_DT",
        arrayOf(arrayOf("dossierConsultation", "DT", "projetEtSonCalendrier", "datePrevuePourLeCommencementDesTravaux")),"DateMonth"),
    XmlPdf("Annee_travaux_DT",
        arrayOf(arrayOf("dossierConsultation", "DT", "projetEtSonCalendrier", "datePrevuePourLeCommencementDesTravaux")),"DateFullYear"),
    XmlPdf("Duree_travaux_DT",
        arrayOf(arrayOf("dossierConsultation", "DT", "projetEtSonCalendrier", "dureeDuChantierEnJours"))),
    XmlPdf("Investigations",
        arrayOf(arrayOf("dossierConsultation", "DT", "investigationsComplementairesDT", "realisationDInvestigationsComplementaires"))),
    XmlPdf("Investigations_complementaires",
        arrayOf(arrayOf("dossierConsultation", "DT", "investigationsComplementairesDT", "motifDeRealisationOuNonDInvestigation"))),
    XmlPdf("Jour_IC",
        arrayOf(arrayOf("dossierConsultation", "DT", "investigationsComplementairesDT", "dateDesInvestigationsComplementaires")),"DateDate"),
    XmlPdf("Mois_IC",
        arrayOf(arrayOf("dossierConsultation", "DT", "investigationsComplementairesDT", "dateDesInvestigationsComplementaires")),"DateMonth"),
    XmlPdf("Annee_IC",
        arrayOf(arrayOf("dossierConsultation", "DT", "investigationsComplementairesDT", "dateDesInvestigationsComplementaires")),"DateFullYear"),
    XmlPdf("IC_avec_DICT",
        arrayOf(arrayOf("dossierConsultation", "DT", "investigationsComplementairesDT", "InvestigationsSusceptibleDeNecessiterUneDICT"))),
    XmlPdf("Envoi_resultats_IC",
        arrayOf(arrayOf("dossierConsultation", "DT", "investigationsComplementairesDT", "envoiDesResultatsAuxExploitantsDOuvragesEtAuxEntreprises"))),
    XmlPdf("Nom_Signataire_DT",
        arrayOf(arrayOf("dossierConsultation", "DT", "signatureDuResponsableDuProjetOuDeSonRepresentant", "nomDuSignataire"))),
    XmlPdf("Nombre_PJ_DT",
        arrayOf(arrayOf("dossierConsultation", "DT", "signatureDuResponsableDuProjetOuDeSonRepresentant", "nombrePagesJointes")))
)

/*
    "No_GU_DICT",
    "No_affaire_executant",
    "Jour_DICT",
    "Mois_DICT",
    "Annee_DICT",
    "Nature_DICT",
    "Executant",
    "Complement_adresse_DICT",
    "Numero_DICT",
    "VoieDICT",
    "Lieudit_BP_DICT",
    "CodePostal_DICT",
    "Commune_DICT",
    "Pays_DICT",
    "SiretDICT1",
    "SiretDICT2",
    "SiretDICT3",
    "SiretDICT4",
    "PersonneContacter_DICT",
    "Telephone_DICT",
    "Fax_DICT",
    "Courriel_DICT",
    "Adresse_DICT",
    "CodePostalTravaux_DICT",
    "CommuneTravaux_DICT",
    "Nb_Communes_DICT",
    "Mode_recepisse_DICT",
    "Plans_taille_DICT",
    "PlanCouleur_DICT",
    "PlansVectoriels_DICT",
    "Plans_Formats_DICT",
    "NatureTravaux1_DICT",
    "NatureTravaux2_DICT",
    "NatureTravaux3_DICT",
    "NatureTravaux4_DICT",
    "NatureTravaux5_DICT",
    "Travaux1_DICT",
    "Travaux2_DICT",
    "Technique_DICT1",
    "Technique_DICT2",
    "Technique_DICT3",
    "Technique_DICT4",
    "Technique_DICT5",
    "Technique_DICT6",
    "Technique_DICT7",
    "Technique_DICT8",
    "Technique_DICT9",
    "Technique_DICT10",
    "AutreTechniqueCase_DICT",
    "Autre_technique_DICT",
    "Profondeur_DICT",
    "Modif_profil_DICT",
    "ResultatsInvestigations_DICT",
    "Distance_m_DICT",
    "Distance_cm_DICT",
    "PlansElecCase_DICT",
    "JourTravaux_DICT",
    "MoisTravaux_DICT",
    "AnneeTravaux_DICT",
    "DureeChantier_DICT",
    "NomSignataire_DICT",
    "NombrePJ_DICT",
    "empriseDT",
    "empriseDICT",
    "communesDT",
    "communesDICT") */
